// Resume data — RU + EN. Returns the right object via getResume(lang).

const RESUME_RU = {
  lang: "ru",
  name: { first: "Дмитрий", last: "Смирнов" },
  role: "Full Stack Engineer",
  location: "Бали, Индонезия",
  tz: "Asia/Makassar",
  email: "dmitry.sonder@gmail.com",
  github: "dmitrysonder",
  githubUrl: "https://github.com/dmitrysonder",
  site: "dmitrysonder.github.io",
  siteUrl: "https://dmitrysonder.github.io",
  handle: "dmk_works",
  intro: "Семь лет строю продукты на стыке web, blockchain и AI — от смарт-контрактов до полных стеков с инфраструктурой, дизайном и платёжными интеграциями.",
  available: "Готов к удалённой работе и командировкам",

  experience: [
    {
      year: "2026 —", now: true,
      role: "Технический директор / CTO",
      company: "SoulBook.io",
      industry: "Indie · AI · Publishing",
      summary: "Запустил с нуля сервис генерации персональных книг с помощью LLM — от дизайна и фронта до бэкенда и деплоя.",
      bullets: [
        "Сделал сервис с нуля: дизайн, бекенд, фронтенд, деплой на VPS через GitHub Actions",
        "Сервис набрал 1 000 пользователей за 2 месяца и продолжает расти",
        "Получил 80 продаж",
        "Интегрировал C-биндинги в Node.js для библиотеки sweph",
        "Реализовал пайплайн генерации книг: обложка, рендеринг PDF, параллельное написание текста, очереди через BullMQ",
      ],
      stack: ["node.js", "llm", "bullmq", "pdf", "github actions", "vps", "design"],
    },
    {
      year: "2025 — 2026",
      role: "Backend Engineer", company: "Fundraise Up",
      industry: "Fundraising · Integrations",
      summary: "Разработка и поддержка интеграций со сторонними CRM — Salesforce, Hubspot, DoubleTheDonation, Zapier. Дежурства, багфиксинг и технические дизайны.",
      bullets: [
        "Сделал нативную синхронизацию Hubspot подписок (recurring donations)",
        "Рефакторинг Error Handling логики в модуле интеграций",
      ],
      stack: ["node.js", "typescript", "hubspot", "salesforce", "zapier"],
    },
    {
      year: "2021 — 2025",
      role: "CTO / Senior Software Engineer", company: "InterSwap",
      industry: "DeFi · Cross-chain",
      summary: "DeFi-стартап. CTO с самого начала — от смарт-контрактов до инфраструктуры и команды.",
      bullets: [
        "Спроектировал и разработал смарт-контракты для кросс-чейн AMM протокола с месседжингом через LayerZero и Axelar, покрыл unit-тестами",
        "Сделал backend + REST API для кеширования данных со смарт-контрактов на NestJS и PostgreSQL",
        "Помогал в разработке фронтенд-приложения на React",
        "Сетапил инфраструктуру и CI/CD: AWS Elastic Beanstalk, AWS Amplify, API Gateway, Docker",
        "Управлял командой из 3 разработчиков и 1 QA",
      ],
      stack: ["solidity", "layerzero", "axelar", "nestjs", "postgresql", "react", "aws", "docker"],
    },
    {
      year: "2023 — 2024",
      role: "Backend Engineer", company: "Skillbox",
      industry: "EdTech",
      summary: "Платформа обучения английскому eng.skillbox.ru. Новый функционал, поддержка, интеграции, анализ ошибок.",
      bullets: [
        "Система SQL-триггеров для event-sourcing калькулируемых данных — −30% медианного времени ответа API",
        "Выкатил в прод платежные интеграции: Сбер Рассрочки, Тинькофф Рассрочки, Всегда Да, Яндекс Сплит",
        "Переписывал фронт на Next.js с GraphQL на tRPC",
      ],
      stack: ["node.js", "next.js", "graphql", "trpc", "sql"],
    },
    {
      year: "2019 — 2023",
      role: "Software Engineer / CEO", company: "Spreadsheet Fund",
      industry: "Indie · Crypto · SaaS",
      summary: "Спроектировал и разработал с нуля Add-on для Google Sheets — автоматизация фондов, портфельный учёт и бухгалтерия.",
      bullets: [
        "API-адаптеры к 15+ криптобиржам и 3 блокчейн-эксплорерам",
        "Процессинг крипто-платежей через Google Apps Script + Coinbase Commerce",
        "UI элементы (меню, окна, попапы) на чистом HTML/CSS/JS",
        "Интеграции с Telegram, Gmail, Google Docs через Node.js и Google API",
        "≈10 000 строк кода, 1 600 пользователей, 10 публичных фондов: CrescoFinance, Rubus.Fund, AltTokenFund",
      ],
      stack: ["google apps script", "node.js", "coinbase commerce", "telegram api", "sql"],
    },
    {
      year: "2021 — 2022",
      role: "Senior Backend & Solidity Engineer", company: "Vaulty.fi",
      industry: "DeFi · Yield",
      summary: "Стратегии DeFi Yield Optimizer для Venus, Alpaca, Belt.fi плюс контракты для токенсейла, вестинга и говернанса.",
      bullets: [
        "Smart-contracts: yield-стратегии, tokensale, vesting, governance",
        "Serverless backend и REST API на AWS Lambda + DynamoDB",
        "Доработка web3-части React-приложения",
        "Графы для TheGraph",
      ],
      stack: ["solidity", "aws lambda", "dynamodb", "react", "the graph"],
    },
    {
      year: "2019 — 2021",
      role: "Senior QA Automation Engineer", company: "EPAM Systems",
      industry: "Enterprise · Healthcare",
      summary: "Фреймворк автоматизации тестирования на WebdriverIO + TypeScript, разработка модулей для PostgreSQL и парсинга медицинских данных.",
      bullets: [
        "Разработка и поддержка фреймворка автотестов",
        "Модуль для работы с PostgreSQL",
        "Модуль парсинга txt-файлов с медицинскими данными",
      ],
      stack: ["webdriverio", "typescript", "postgresql"],
    },
    {
      year: "2018",
      role: "Ethereum Smart Contract Developer", company: "AltTokenFund / CrescoFinance",
      industry: "DeFi · ERC-20",
      summary: "Backend и смарт-контракт для автоматизации работы паевого фонда с ERC-20 токеном.",
      bullets: [
        "Google Sheets, синхронизирующийся со смарт-контрактом — учёт и управление фондом",
        "Telegram-бот, подписывающий и отправляющий транзакции записи цены пая",
        "Технический WhitePaper для AltTokenFund",
        "Внедрил систему еще в 2 публичных фонда (CrescoFinance, RubusFund)",
      ],
      stack: ["solidity", "node.js", "web3.js", "telegraf.js"],
    },
  ],

  projects: [
    {
      name: "SoulBook.io", status: "live",
      desc: "Сервис генерации персональных книг с помощью LLM. Дизайн, бэкенд, фронтенд, инфраструктура — всё с нуля. Параллельная генерация текста, рендер PDF, очереди BullMQ.",
      metrics: [
        { value: "1 000+", label: "Пользователей" },
        { value: "80", label: "Продаж" },
        { value: "2 мес", label: "До трекшна" },
      ],
    },
    {
      name: "InterSwap", status: "shipped",
      desc: "Кросс-чейн AMM с месседжингом через LayerZero и Axelar. CTO, смарт-контракты, NestJS бэк, инфраструктура на AWS, команда из 4 человек.",
      metrics: [
        { value: "4y", label: "В роли CTO" },
        { value: "4", label: "В команде" },
        { value: "x-chain", label: "Архитектура" },
      ],
    },
    {
      name: "Spreadsheet Fund", status: "shipped",
      desc: "Add-on для Google Sheets для автоматизации криптофондов. 10k+ строк Apps Script, интеграции с 15 биржами, процессинг платежей.",
      metrics: [
        { value: "1 600", label: "Пользователей" },
        { value: "10", label: "Фондов" },
        { value: "15+", label: "Бирж" },
      ],
    },
    {
      name: "Skillbox · Eng", status: "shipped",
      desc: "Платформа обучения английскому. Event-sourcing на SQL-триггерах, четыре платёжные интеграции, миграция фронта на Next.js + tRPC.",
      metrics: [
        { value: "−30%", label: "API latency" },
        { value: "4", label: "Платёжки" },
        { value: "tRPC", label: "Стек" },
      ],
    },
  ],

  skills: {
    languages: ["TypeScript", "JavaScript", "Solidity", "Python", "SQL"],
    backend: ["Node.js", "NestJS", "tRPC", "GraphQL", "Sequelize", "Prisma", "BullMQ"],
    frontend: ["React", "Next.js", "HTML", "CSS"],
    blockchain: ["EVM", "Hardhat", "LayerZero", "Axelar", "The Graph", "web3.js"],
    infra: ["AWS", "Docker", "PostgreSQL", "MongoDB", "DynamoDB", "GitHub Actions", "Google Cloud"],
    other: ["Google Apps Script", "QA Automation", "Технический дизайн"],
  },

  education: { degree: "Высшее", school: "Балтийский федеральный университет им. И. Канта", schoolShort: "БФУ им. Канта" },
  certs: [{ name: "Ethereum and Solidity: The Complete Developer's Guide", issuer: "Udemy", date: "Май 2026" }],
  langs: [{ name: "Русский", level: "Native" }, { name: "English", level: "B2" }],

  ui: {
    available: "Доступен",
    nowAt: "Currently",
    nowLine: "CTO @ SoulBook.io — генерация книг с помощью LLM",
    openToWork: "Открыт к работе",
    contactStatus: "Status",
    contactSite: "Сайт",
    emailHint: "Email · кликни, чтобы скопировать",
    copied: "скопировано",
    nav: { exp: "Опыт", proj: "Проекты", skills: "Навыки", contact: "Контакты" },
    sections: {
      timeline: { num: "01 — Карьера", title: "Таймлайн" },
      exp:      { num: "02 — Опыт",    title: "Семь лет, восемь ролей." },
      proj:     { num: "03 — Избранное", title: "Проекты с цифрами." },
      skills:   { num: "04 — Стек",     title: "Чем пишу." },
      side:     { num: "05 — Прочее",   title: "Образование, языки, сертификаты." },
    },
    stats: [
      { value: "8", label: "Ролей / компаний", note: "С 2018" },
      { value: "7", label: "Лет в инженерии", note: "Backend, web3, full-stack" },
      { value: "2 600+", label: "Пользователей продуктов", note: "SoulBook + Spreadsheet Fund" },
      { value: "15+", label: "Интеграций бирж", note: "Криптовалюты, платежи, CRM" },
    ],
    skillGroups: [
      { key: "languages", label: "Языки" },
      { key: "backend", label: "Backend" },
      { key: "frontend", label: "Frontend" },
      { key: "blockchain", label: "Blockchain" },
      { key: "infra", label: "Infra & Data" },
      { key: "other", label: "Прочее" },
    ],
    skillsAside: "Компетенции",
    sideLabels: { langs: "Языки", edu: "Образование", certs: "Сертификаты" },
    nowTag: "сейчас",
    statusLive: "Live",
    statusShipped: "Shipped",
    footerCta: ["Есть интересная задача?", "Напишите"],
    footerCopy: "© 2026 · Смирнов Дмитрий",
    metaLine: ["Открыт к работе"],
    tzCity: "Бали",
    locale: "ru-RU",
  },
};

const RESUME_EN = {
  lang: "en",
  name: { first: "Dmitry", last: "Smirnov" },
  role: "Full Stack Engineer",
  location: "Bali, Indonesia",
  tz: "Asia/Makassar",
  email: "dmitry.sonder@gmail.com",
  github: "dmitrysonder",
  githubUrl: "https://github.com/dmitrysonder",
  site: "dmitrysonder.github.io",
  siteUrl: "https://dmitrysonder.github.io",
  handle: "dmk_works",
  intro: "Seven years building products at the intersection of web, blockchain and AI — from smart contracts to full stacks with infrastructure, design and payment integrations.",
  available: "Open to remote work and business trips",

  experience: [
    {
      year: "2026 —", now: true,
      role: "CTO / Founding Engineer",
      company: "SoulBook.io",
      industry: "Indie · AI · Publishing",
      summary: "Launched a service from scratch that generates personalized books with LLMs — from design and frontend to backend and deploy.",
      bullets: [
        "Built the service end-to-end: design, backend, frontend, deploy to VPS via GitHub Actions",
        "Reached 1,000 users in 2 months and still growing",
        "Closed 80 sales",
        "Integrated C bindings into Node.js for the sweph library",
        "Built the book-generation pipeline: cover, PDF rendering, parallel text writing, BullMQ queues",
      ],
      stack: ["node.js", "llm", "bullmq", "pdf", "github actions", "vps", "design"],
    },
    {
      year: "2025 — 2026",
      role: "Backend Engineer", company: "Fundraise Up",
      industry: "Fundraising · Integrations",
      summary: "Built and maintained third-party CRM integrations — Salesforce, Hubspot, DoubleTheDonation, Zapier. On-call, bugfixing and technical design.",
      bullets: [
        "Native Hubspot sync for recurring donations",
        "Refactored error-handling across the integrations module",
      ],
      stack: ["node.js", "typescript", "hubspot", "salesforce", "zapier"],
    },
    {
      year: "2021 — 2025",
      role: "CTO / Senior Software Engineer", company: "InterSwap",
      industry: "DeFi · Cross-chain",
      summary: "DeFi startup. CTO from day one — smart contracts, infrastructure and team.",
      bullets: [
        "Designed and built smart contracts for a cross-chain AMM with LayerZero and Axelar messaging, covered with unit tests",
        "Built a NestJS + PostgreSQL backend and REST API to cache on-chain data",
        "Contributed to the React frontend",
        "Set up infrastructure and CI/CD: AWS Elastic Beanstalk, AWS Amplify, API Gateway, Docker",
        "Led a team of 3 engineers and 1 QA",
      ],
      stack: ["solidity", "layerzero", "axelar", "nestjs", "postgresql", "react", "aws", "docker"],
    },
    {
      year: "2023 — 2024",
      role: "Backend Engineer", company: "Skillbox",
      industry: "EdTech",
      summary: "English-learning platform eng.skillbox.ru. New features, support, integrations, incident response.",
      bullets: [
        "SQL-trigger event-sourcing system for computed data — cut median API latency by 30%",
        "Shipped four payment integrations to prod: Sber, Tinkoff, Vsegda Da, Yandex Split",
        "Migrated frontend from GraphQL to tRPC on Next.js",
      ],
      stack: ["node.js", "next.js", "graphql", "trpc", "sql"],
    },
    {
      year: "2019 — 2023",
      role: "Software Engineer / CEO", company: "Spreadsheet Fund",
      industry: "Indie · Crypto · SaaS",
      summary: "Designed and built a Google Sheets add-on from scratch — fund automation, portfolio tracking and accounting.",
      bullets: [
        "API adapters for 15+ crypto exchanges and 3 blockchain explorers",
        "Crypto payment processing via Google Apps Script + Coinbase Commerce",
        "UI elements (menus, modals, popups) in plain HTML/CSS/JS",
        "Integrations with Telegram, Gmail, Google Docs via Node.js and Google APIs",
        "≈10,000 LOC, 1,600 users, 10 public funds: CrescoFinance, Rubus.Fund, AltTokenFund",
      ],
      stack: ["google apps script", "node.js", "coinbase commerce", "telegram api", "sql"],
    },
    {
      year: "2021 — 2022",
      role: "Senior Backend & Solidity Engineer", company: "Vaulty.fi",
      industry: "DeFi · Yield",
      summary: "DeFi Yield Optimizer strategies for Venus, Alpaca, Belt.fi plus tokensale, vesting and governance contracts.",
      bullets: [
        "Smart contracts: yield strategies, tokensale, vesting, governance",
        "Serverless backend and REST API on AWS Lambda + DynamoDB",
        "Web3 work on the React app",
        "Subgraphs for TheGraph",
      ],
      stack: ["solidity", "aws lambda", "dynamodb", "react", "the graph"],
    },
    {
      year: "2019 — 2021",
      role: "Senior QA Automation Engineer", company: "EPAM Systems",
      industry: "Enterprise · Healthcare",
      summary: "Test-automation framework on WebdriverIO + TypeScript, plus modules for PostgreSQL and medical-data parsing.",
      bullets: [
        "Built and maintained the autotest framework",
        "Module for PostgreSQL access",
        "Module for parsing medical-data .txt files",
      ],
      stack: ["webdriverio", "typescript", "postgresql"],
    },
    {
      year: "2018",
      role: "Ethereum Smart Contract Developer", company: "AltTokenFund / CrescoFinance",
      industry: "DeFi · ERC-20",
      summary: "Backend and smart contract automating an ERC-20-backed investment fund.",
      bullets: [
        "Google Sheets synced with the smart contract — fund accounting and management",
        "Telegram bot that signs and broadcasts share-price transactions",
        "Technical WhitePaper for AltTokenFund",
        "Rolled the system out to 2 more public funds (CrescoFinance, RubusFund)",
      ],
      stack: ["solidity", "node.js", "web3.js", "telegraf.js"],
    },
  ],

  projects: [
    {
      name: "SoulBook.io", status: "live",
      desc: "Personalized book generation via LLMs. Design, backend, frontend, infrastructure — all from scratch. Parallel text generation, PDF rendering, BullMQ queues.",
      metrics: [
        { value: "1,000+", label: "Users" },
        { value: "80", label: "Sales" },
        { value: "2 mo", label: "To traction" },
      ],
    },
    {
      name: "InterSwap", status: "shipped",
      desc: "Cross-chain AMM with LayerZero and Axelar messaging. CTO, smart contracts, NestJS backend, AWS infrastructure, team of 4.",
      metrics: [
        { value: "4y", label: "As CTO" },
        { value: "4", label: "Team size" },
        { value: "x-chain", label: "Architecture" },
      ],
    },
    {
      name: "Spreadsheet Fund", status: "shipped",
      desc: "Google Sheets add-on for crypto fund automation. 10k+ LOC of Apps Script, integrations with 15 exchanges, payment processing.",
      metrics: [
        { value: "1,600", label: "Users" },
        { value: "10", label: "Funds" },
        { value: "15+", label: "Exchanges" },
      ],
    },
    {
      name: "Skillbox · Eng", status: "shipped",
      desc: "English-learning platform. SQL-trigger event sourcing, four payment integrations, frontend migration to Next.js + tRPC.",
      metrics: [
        { value: "−30%", label: "API latency" },
        { value: "4", label: "Payments" },
        { value: "tRPC", label: "Stack" },
      ],
    },
  ],

  skills: {
    languages: ["TypeScript", "JavaScript", "Solidity", "Python", "SQL"],
    backend: ["Node.js", "NestJS", "tRPC", "GraphQL", "Sequelize", "Prisma", "BullMQ"],
    frontend: ["React", "Next.js", "HTML", "CSS"],
    blockchain: ["EVM", "Hardhat", "LayerZero", "Axelar", "The Graph", "web3.js"],
    infra: ["AWS", "Docker", "PostgreSQL", "MongoDB", "DynamoDB", "GitHub Actions", "Google Cloud"],
    other: ["Google Apps Script", "QA Automation", "Technical design"],
  },

  education: { degree: "BSc, Computer Science", school: "Immanuel Kant Baltic Federal University", schoolShort: "IKBFU" },
  certs: [{ name: "Ethereum and Solidity: The Complete Developer's Guide", issuer: "Udemy", date: "May 2026" }],
  langs: [{ name: "Russian", level: "Native" }, { name: "English", level: "B2" }],

  ui: {
    available: "Available",
    nowAt: "Currently",
    nowLine: "CTO @ SoulBook.io — personalized books via LLM",
    openToWork: "Open to work",
    contactStatus: "Status",
    contactSite: "Site",
    emailHint: "Email · click to copy",
    copied: "copied",
    nav: { exp: "Experience", proj: "Projects", skills: "Skills", contact: "Contact" },
    sections: {
      timeline: { num: "01 — Career", title: "In parallel, not in series." },
      exp:      { num: "02 — Experience", title: "Seven years, eight roles." },
      proj:     { num: "03 — Selected work", title: "Projects with numbers." },
      skills:   { num: "04 — Stack", title: "What I write with." },
      side:     { num: "05 — More", title: "Education, languages, certificates." },
    },
    stats: [
      { value: "8", label: "Roles / companies", note: "Since 2018" },
      { value: "7", label: "Years engineering", note: "Backend, web3, full-stack" },
      { value: "2,600+", label: "Users across products", note: "SoulBook + Spreadsheet Fund" },
      { value: "15+", label: "Exchange integrations", note: "Crypto, payments, CRM" },
    ],
    skillGroups: [
      { key: "languages", label: "Languages" },
      { key: "backend", label: "Backend" },
      { key: "frontend", label: "Frontend" },
      { key: "blockchain", label: "Blockchain" },
      { key: "infra", label: "Infra & Data" },
      { key: "other", label: "Other" },
    ],
    skillsAside: "Competencies",
    sideLabels: { langs: "Languages", edu: "Education", certs: "Certificates" },
    nowTag: "now",
    statusLive: "Live",
    statusShipped: "Shipped",
    footerCta: ["Got an interesting problem?", "Write to"],
    footerCopy: "© 2026 · Dmitry Smirnov",
    metaLine: ["Open to work"],
    tzCity: "Bali",
    locale: "en-US",
  },
};

function getResume(lang) {
  return lang === "en" ? RESUME_EN : RESUME_RU;
}

Object.assign(window, { RESUME_RU, RESUME_EN, getResume });
// Keep backwards-compat global
window.RESUME = RESUME_RU;
